// packages/vue-ui/src/components/AddressFormField.vue
<script setup lang="ts">
import type { LocnativeClient } from "@locnative/sdk";
import { computed } from "vue";
import { cn } from "../utils/cn";

// Extra attrs (disabled, placeholder, minCharsToSearch, @select, ...) pass
// straight through to the wrapped AddressAutocomplete via $attrs. `client` is
// declared explicitly so the required-prop contract is statically satisfied.
defineOptions({ inheritAttrs: false });

const props = defineProps<{
	/** Required. SDK client created with `createLocnativeClient`. */
	client: LocnativeClient;
	/** Class applied to the error text element. */
	errorClass?: string;
	/** External error message; renders below the field and reddens the label. */
	error?: string;
	/** id forwarded to the input element. */
	id?: string;
	/** Required. Field label rendered above the input. */
	label: string;
	/** Class applied to the label element. */
	labelClass?: string;
	/** Mark the input as required. */
	required?: boolean;
}>();

const fieldId = computed(() => props.id ?? "locnative-field");
</script>

<template>
  <div class="flex flex-col gap-2" data-slot="address-form-field">
    <label
      :class="cn('block font-medium text-gray-900 text-sm', props.labelClass)"
      :for="fieldId"
    >
      {{ props.label }}
      <span v-if="props.required" aria-hidden="true" class="ml-1 text-red-600">*</span>
    </label>

    <AddressAutocomplete
      v-bind="$attrs"
      :id="fieldId"
      :client="props.client"
      :error="props.error"
      :required="props.required"
    />

    <p
      v-if="props.error"
      aria-live="polite"
      :class="cn('text-red-600 text-sm', props.errorClass)"
      role="alert"
    >
      {{ props.error }}
    </p>
  </div>
</template>

// packages/react-ui/src/components/address-form-field.tsx
import type { ReactNode } from "react";
import { cn } from "../utils/cn";
import type { AddressAutocompleteProps } from "./address-autocomplete";
import { AddressAutocomplete } from "./address-autocomplete";

export interface AddressFormFieldProps extends AddressAutocompleteProps {
	/** Class applied to the error text element. */
	errorClassName?: string;
	/** Required. Field label rendered above the input. */
	label: string;
	/** Class applied to the label element. */
	labelClassName?: string;
}

export function AddressFormField({
	label,
	labelClassName,
	errorClassName,
	error,
	required,
	disabled,
	id: customId,
	className,
	...autocompleteProps
}: AddressFormFieldProps): ReactNode {
	const id = customId ?? "locnative-field";

	return (
		<div className="flex flex-col gap-2" data-slot="address-form-field">
			<label
				className={cn(
					"block font-medium text-gray-900 text-sm",
					labelClassName
				)}
				htmlFor={id}
			>
				{label}
				{required && (
					<span aria-hidden="true" className="ml-1 text-red-600">
						*
					</span>
				)}
			</label>

			<AddressAutocomplete
				{...autocompleteProps}
				className={className}
				disabled={disabled}
				error={error}
				id={id}
				required={required}
			/>

			{error && (
				<p
					aria-live="polite"
					className={cn("text-red-600 text-sm", errorClassName)}
					role="alert"
				>
					{error}
				</p>
			)}
		</div>
	);
}
